name: Java CI Maven EDURIO Survey auto tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Create Allure results directory
      run: mkdir -p target/allure-results
      
    - name: Build Maven project
      run: mvn -B clean compile

    - name: Install Allure Commandline Tool
      run: |
            wget https://github.com/allure-framework/allure2/releases/download/2.22.0/allure-2.22.0.zip
            unzip allure-2.22.0.zip -d allure
      
    - name: Run Tests and Generate Allure Report
      run: |
        mvn clean test
        ./allure/allure-2.22.0/bin/allure generate allure-results --clean -o target/allure-report

    - name: Publish Allure Report
      uses: actions/upload-artifact@v3
      with:
          name: allure-report
          path: target/allure-report